### ISSUE TITLE
Multi-objective Genetic Algorithm Optimization of Water Supply Systems

### ISSUE THREAD

**Issue by rogersisci** [sscchan/Genetic-Algorithm-Optimization-of-Water-Supply-System#1]
hello Stephen Chan, In the project "Multi-objective Genetic Algorithm Optimization of Water Supply Systems " the files:

EPANETInputLocation = "c:\EPATEST\robmanualnetwork.inp";
pipeDatabaseInputLocation = "c:\EPATEST\robtestpipedatabase.txt";

Could you provide us with the structure of those files? Thank you for your great contribution.

**Comment by rogersisci** [comment]
Please

**Comment by sscchan** [comment]
The code is from an incomplete backup from an old university project. I'm not sure what you're going to do with it.

Since it was an incomplete backup, I no longer have access to the input file.

Anyhow the robmanualnetwork.inp is a EPANET text input file (not binary format). 
robtestpipedatabase.txt should be (I think) a csv of a list of candidate pipes that is used for the GA. (you'll have to checkthe ingestion code to confirm).

I can give you some advice if you tell me what you're going to do with it, are you doing a specific research project (honors, masters, phD)?

**Comment by rogersisci** [comment]
Thank you.
I get an error in vector in the filerobtestpipedatabase.txt  when I put pipes and diameter. I have a thesis project applying genetic algorithms in a driving line that supplies a city of Arequipa in Peru and I was looking for an optimized method for the case study.

**Comment by rogersisci** [comment]
Thank you.
I get an error in vector in the filerobtestpipedatabase.txt  when I put pipes and diameter. I have a thesis project applying genetic algorithms in a driving line that supplies a city of Arequipa in Peru and I was looking for an optimized method for the case study.

**Comment by sscchan** [comment]
The ingestion code of interest:
https://github.com/sscchan/Genetic-Algorithm-Optimization-of-Water-Supply-System/blob/master/GAW/pipeDatabaseClass.cpp#L54-L93

As I mentioned before, the code is incomplete (I think), so even if you get the the input working I'm not sure it'll create an output.

If you know how to code in C++ then you can take what I have a modify it to work. If you driving line design is relatively simple, I wouldn't rule out enumeration of the entire problem space if you can use some heuristics to narrow down the pipe / pump component choices.

**Comment by rogersisci** [comment]
estuve estudiando su articulo
http://sscchan.github.io/blog/optimizing-water-supply-networks-with-genetic-algorithmn-part-i/
si tambien me podria recomendar o proporcionar informacion con la cual fue trabajado el codigo.

muchas gracias por su ayuda

**Comment by rogersisci** [comment]
I was studying your article
http://sscchan.github.io/blog/optimizing-water-supply-networks-with-genetic-algorithmn-part-i/
if you could also recommend or provide information with which the code was worked.

thank you very much for your help

**Comment by sscchan** [comment]
@rogersisci take a look at available GA library (https://www.quora.com/What-are-some-good-genetic-programming-libraries-in-C++), then interface it with EPANET's programmer toolkit: https://www.epa.gov/water-research/epanet. You'll need to do a bunch of code to glue them together.
